services:
  - type: web
    name: simplify-ai-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: |
      echo "Installing frontend dependencies..." && \
      npm --prefix ./frontend/ai-learning-assistant install && \
      echo "Building frontend..." && \
      npm --prefix ./frontend/ai-learning-assistant run build && \
      echo "Installing backend dependencies..." && \
      npm --prefix ./backend install
    startCommand: npm --prefix ./backend start
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
